# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 10:02
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('img', models.ImageField(default=None, upload_to='pic')),
                ('realname', models.CharField(default='None', max_length=30)),
                ('dt', models.DateTimeField(verbose_name='DatetimeCommit')),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='LastPostID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdt', models.DateTimeField(default=datetime.datetime(2017, 5, 19, 10, 2, 31, 172755), verbose_name='DatetimeCommit')),
                ('postid', models.IntegerField()),
            ],
        ),
    ]
