# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170519_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['dt']},
        ),
        migrations.AlterField(
            model_name='lastpostid',
            name='postdt',
            field=models.DateTimeField(verbose_name='DatetimeCommit'),
        ),
    ]
