# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 07:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170519_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
